module.exports = {
    titleSuffix: " | Award",
    titles: {
        '/': 'Home',
        '/partners': 'Partners',
        '/dashboard': 'Guilds',
        '/discover': 'Discover',
        '/browse': 'Discover',
        '/team': 'Team',
        '/tos': 'Terms of Service',
        '/privacy': 'Privacy Policy',
        '/dashboard/[id]': 'Guild Home',
        '/dashboard/[id]/giveaways/create': 'Create a Giveaway',
        '/account/connections': 'Your Connections',
        '/account/redeem': 'Redeem Code',
        '/boosts/[id]': 'Guild Boosts',
        '/g/[id]': 'Giveaway',
        '/user/[id]': 'User Profile',
        '/404': '404',
        '/dashboard/added': 'Thanks for adding our bot!',
        '/dashboard/[id]/settings': 'Settings',
        '/dashboard/[id]/giveaways/active': 'Active Giveaways',
        '/dashboard/[id]/giveaways/ended': 'Ended Giveaways',
        '/dashboard/[id]/giveaways': 'All Giveaways',
        '/panel': 'Panel',
        '/panel/partners': 'Manage Partners',
        '/panel/online': 'Online Users',
        '/panel/promocode': 'Promocode Create'
    },
};